### ISSUE TITLE
Install TAP driver loop on Windows 10

### ISSUE THREAD

**Issue by psdavid-muc** [Securepoint/openvpn-client#16]
Updating the Securepoint SSL VPN client on a Windows 10 (current release, latest updates) machine created some issues for me:

- after starting the Client and importing my configuration, the Client asks me to install TAP drivers, after acknowledging and trying to reconnect die Client asks again and again and again
- log file says "ERROR: All TAP-Windows adapters on this system are currently in use"
- in the device manager i see for every retry a TAP device with a exclamation mark and a error message 

> "Die digitale Signatur der für dieses Gerät erforderlichen Treiber kann nicht überprüft werden. Bei einer vor Kurzem durchgeführten Änderung an Hardware oder Software wurde möglicherweise eine Datei installiert, die falsch signiert oder beschädigt ist. Möglicherweise handelt es sich auch um schädliche Software einer unbekannten Quelle. (Code 52)"

- Rebooting, reinstalling, purging does not work.
Yet, i worked around that by installing a previous version (2.0.20) of the client.

**Comment by sweikelt** [comment]
same problem here.
i installed 2.0.25 which also worked

**Comment by fraenki** [comment]
@sweikelt Please retest with 2.0.26, it was just released an hour ago:
https://github.com/Securepoint/openvpn-client/releases

**Comment by sweikelt** [comment]
@fraenki - i know - that's y i tested it 30mins ago -> where the release was 18 mins old ;)
--> so still same problem :(

**Comment by fraenki** [comment]
This issue can be solved by installing the properly signed TAP driver (in addition to the Securepoint SSL VPN client):

https://build.openvpn.net/downloads/releases/tap-windows-9.24.2-I601-Win10.exe
https://chocolatey.org/packages/tapwindows

**Comment by QtOlli** [comment]
Hello,

please try the new 2.0.27 release.

kind regards
Oliver
