### ISSUE TITLE
Window always op to the Top of Position

### ISSUE THREAD

**Issue by lordgit** [Securepoint/openvpn-client#19]
When you use  Taskbar in top of the screen and than open the window of the openvpn-client, it's open ouside the visible screen. Always open to top of the current position.

**Comment by DNS-HRA** [comment]
can confirm this sometimes happens. You should be able to move the position by draging the icon to the left.

**Comment by reemaldeirani-sp** [comment]
Closed, cannot be reproduced in the newest version.
