### ISSUE TITLE
TAP driver failed to install on some of systems of win7

### ISSUE THREAD

**Issue by zhezhe168** [Securepoint/openvpn-client#20]
TAP driver failed to install on some of systems of win7

**Comment by QtOlli** [comment]
Hi, 

please make sure that all Windows 7 are patched for the sha2 support.
<html>
<body>


March 12, 2019 | Stand Alone security updates KB4474419 and KB4490628 released to introduce SHA-2 code sign support.
-- | --



</body>
</html>
Source: https://support.microsoft.com/en-us/topic/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus-64d1c82d-31ee-c273-3930-69a4cde8e64f

If the issue still exists, please provide more informations about the affected windows systems.

Thanks
Oliver

**Comment by zhezhe168** [comment]
I found the information of this error from Google,then I installed sha2 patch,it works,thanks.
