### ISSUE TITLE
Import Problems with Version: 2.0.36

### ISSUE THREAD

**Issue by hosse** [Securepoint/openvpn-client#23]
Windows10 Build 19044.1586
ovpn-client: 2.0.36

Hello,

Two problems:
1) Importing a file formatted in "UTF8" destroys special letters like "ß" in the German language.
Only a conversion from "UTF8" to "ANSI" and edit the file can fix the problem.
Example: In the  *.ovpn-File
`verify-x509-name` "C=xx, ST=xx, L=Gie**ÃŸ**en, O=xxx, emailAddress=xxx, CN=xxx" subject`
here ÃŸ=ß

2) When importing with three files *.key, *.ovpn and *.p12 with Importfunction, then the `*.key` file is not imported.

I have been using your client for years and I can only thank you very much for your work.

Greetings Mario Hosse

**Comment by hosse** [comment]
Hello Oliver,

thank you for your quick reply.

To your question:

Yes, ovpn-file has:
pkcs12 xxx.p12
tls-crypt xxx.key

without quotes.

regards,
Mario

**Comment by QtOlli** [comment]
Hello Mario,

thank you very much for your additonal informations. The `tls-crypt` is missing in the import keyword list.
We fix it in the next release.

For your first issue we need still to find the culprit. I hope we fixed it in the next release, too.

Thanks again!

regards,
Oliver

**Comment by hosse** [comment]
Thank you for the answers to my questions. I will wait for the next release then.
