### ISSUE TITLE
2.0.38 Release Notes

### ISSUE THREAD

**Issue by klou** [Securepoint/openvpn-client#25]
I see that 2.0.38 is available on Sourceforge.

Are there are any Release Notes?

**Comment by QtOlli** [comment]
Hi klou,

thank your very much for reporting this issue! 
We've added the missing releases(github) and release notes(sourceforge).

Links
https://sourceforge.net/p/securepoint/news/2022/11/2038-is-now-available/
https://github.com/Securepoint/openvpn-client/releases/tag/2.0.38

kind regards,
Oliver
