### ISSUE TITLE
Tray icon is not showing up

### ISSUE THREAD

**Issue by tzsolti** [Securepoint/openvpn-client#26]
Since a couple of days, the SSL VPN client system tray icon is not showing up anymore. I have already checked, it is not hidden, the "SSLVpnClient.exe -manage" process is running, and also the Securepoint VPN service is running.
Tried to reinstall the latest version of the client (2.0.38), but the issue was still present. I have tried to play around with the compatibility settings of the shortcut, then when I have checked the high DPI related settings, the tray icon showed up. But next day the issue came back, and since then those DPI related compatibility settings won't help.
Sometimes the tray icon shows up, but when hovering the mouse, it disappears (while the process keeps running).
I'm running Windows 11 x64 version 22H2 (build 22621.819). 
Before this issue, I've been using the Securepoint SSL VPN client without any problems for years.

**Comment by reemaldeirani-sp** [comment]
Closed, cannot be reproduced in the newest version.
