### ISSUE TITLE
Use of script-security greater than 1. This connection is rejected

### ISSUE THREAD

**Issue by sdbbs** [Securepoint/openvpn-client#27]
I've been trying to connect to a work OpenVPN server; usually it just works, but somehow this time it did not, so I updated to latest Securepoint SSL VPN client (2.0.38).

When I try to connect I get this message in the log:

> ERROR: Unsafe configuration found: use of script-security greater than 1. This connection is rejected! For further informations see: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4, section: script-security level

![image](https://user-images.githubusercontent.com/48317456/212576201-7c3df460-3827-4fc5-9b24-a6b9fa81d58d.png)

I checked the .ovpn config via Quick Edit, there was a script-security entry there which had value 3 - I changed that to 1 and clicked OK; apparently that value did get saved:

![image](https://user-images.githubusercontent.com/48317456/212576316-4fd77813-5c68-46dd-8c7d-fefbf9ad513f.png)

... however, I still cannot connect, with the same error message.

Maybe there is no connectivity to the OpenVPN, but I cannot confirm it, I know that the server has ping disabled, so I don't know of any other way to check.

Does this error message have anything to do with script-security entry, and how do I obtain correct behavior again?

**Comment by QtOlli** [comment]
Hello, 

thank you very much for reporting this issue.
It will be fixed in 2.0.39 which released soon.

kind regards,
Oliver
