### ISSUE TITLE
Update to client for security vulnerabilities in OpenSSL

### ISSUE THREAD

**Issue by peterfarrant** [Securepoint/openvpn-client#28]
Is there intended to be a version update soon to update the version of OpenSSL included given a number of CVE reported since the version included in the last release 2.0.38

**Comment by QtOlli** [comment]
Hello, 

In 2.0.39 OpenSSL is updated to the latest version. 2.0.39 will be released soon.

kind regards,
Oliver

**Comment by QtOlli** [comment]
Fixed in 2.0.39
