### ISSUE TITLE
OTP challenge doesn't work

### ISSUE THREAD

**Issue by a2019105466-masters** [Securepoint/openvpn-client#29]
Securepoint SSL VPN Version 2.0.33
OTP Challenge doesn't request code even with Use Interact enabled.
Log show OTP: Challenge
ovpn has static-challenge "OTP" 1

![Captura de ecrã 2023-08-17 093302](https://github.com/Securepoint/openvpn-client/assets/127320154/fa0bbb39-54c2-47a9-a5e8-1932b5165b71)

![Captura de ecrã 2023-08-17 093449](https://github.com/Securepoint/openvpn-client/assets/127320154/42cfb4c9-9a48-44a3-bebd-425f3bc56d0c)

**Comment by FabioMenge** [comment]
Hello,

change your Configuration from
static-challenge "OTP" 1
to
static-challenge "CHALLENGE: Please enter token PIN" *****

kind regards
Fabio
