### ISSUE TITLE
2.0.41 PKCS12 Error at empty Password field

### ISSUE THREAD

**Issue by robmo86** [Securepoint/openvpn-client#31]
Hey guys,

at Client Version 2.0.4.1 you have to enter a password for the PKCS12-File you are using.

If you have a container without a Password and entering no password in the prompt, the client disconnects with an error.

Before 2.0.41 it was possible using an container without password.

Even in the Windows Certificate Store you can import an Container without a password.

A Fix would be kind.

Thanks and Regards
Robert

**Comment by FabioMenge** [comment]
Helllo,

to solve the problem quickly, add "providers legacy default" to your config file.
However, you should recreate your pkcs12  with Openssl3 and a newer cypher.

kind regards
Fabio
