### ISSUE TITLE
Windows Package Manager

### ISSUE THREAD

**Issue by frauhottelmann** [Securepoint/openvpn-client#32]
Hi there,

Would it be possible to add the OpenVPN-Client to Winget? It would make updates much easier since I am using it on quite a few devices.

[Submit packages to Windows Package Manager](https://learn.microsoft.com/en-us/windows/package-manager/package/)

Thanks

**Comment by HRA42** [comment]
We can do this ourselves:

https://github.com/microsoft/winget-pkgs

**Comment by HRA42** [comment]
@frauhottelmann:

Done:
https://github.com/microsoft/winget-pkgs/pull/146952

Should be available soon

**Comment by HRA42** [comment]
It's available now :)

`winget install SecurepointGmbH.SecurepointSSLVPN`
