### ISSUE TITLE
Password starting with ";" is not working

### ISSUE THREAD

**Issue by WebnetMobile** [Securepoint/openvpn-client#5]
I noticed that if you want to use connection with authentication then password cannot start with ";" (semicolon) as it simply does not work at all. Once semicolon is removed or replaced with other character it all works again. I haven't checked if semicolon in the middle of passphrase is causing the same problems though

**Comment by QtOlli** [comment]
This issue should be fixed since 2.0.16.

**Comment by Neustradamus** [comment]
@WebnetMobile: Can you confirm that it works correctly?

@QtOlli: Have you tested all other different characters?

Example:
`² & " ' { } [ ] ( ) - _ \ / ^ @ = ¨ % $ £ ¤ * µ ! ? : ; .`
