### ISSUE TITLE
Silent install strings?

### ISSUE THREAD

**Issue by klou** [Securepoint/openvpn-client#9]
Can you provide any documentation regarding silent install strings for the 2.x EXE's?

**Comment by wget** [comment]
I have the same issue. I'm currently updating [Securepoint SSL VPN on Chocolatey](https://chocolatey.org/packages/securepointsslvpn), but I need to have a complete silent install.

What I see here is that all arguments I pass to the exe are automatically forwarded to the msi. The exe has actually msi files, certificates and other microsoft runtime c++ executables in it.

@fschaefer We need a silent install flag here! :-)  Since your exe basically just asks in which language (German or English), being able to specify the language as well from the command line would be nice.

**Comment by maxdelorme** [comment]
https://dpdevilliers.com/tag/securepoint/

**Comment by wget** [comment]
@QtOlli ping?

**Comment by fraenki** [comment]
We're interested in this too.

**Comment by fraenki** [comment]
I had a great conversation with the guys from Securepoint. Starting with release 2.0.26 they provide the MSI file in addition to the EXE installation file as regular download:
https://github.com/Securepoint/openvpn-client/releases

Furthermore the following documentation was provided for scripted/silent installations:

#### default installation for Windows 10
`msiexec /i openvpn-client-installer-2.0.26.msi CWINVERSION=10`

#### default installation for Windows 7
`msiexec /i openvpn-client-installer-2.0.26.msi CWINVERSION=7`

#### default installation in englisch for Windows 10
`msiexec /i openvpn-client-installer-2.0.26.msi TRANSFORMS=":en-us.mst" CWINVERSION=10`

#### silent installation
use parameter` /qn:` for installation without user-interaction and no GUI

**Comment by fraenki** [comment]
@wget Could you update the choco package to use the new MSI file with the appropiate parameters? :)

**Comment by wget** [comment]
@fraenki Yes, possible. I added this to my todo for the week-end.
My Windows dev machines are currently down. Will get them back on Saturday :)

**Comment by wget** [comment]
> @fraenki Yes, possible. I added this to my todo for the week-end.
> My Windows dev machines are currently down. Will get them back on Saturday :)

Published: https://chocolatey.org/packages/securepointsslvpn/

I think we can close this issue now we have the silent args available and the msi installer.

**Comment by klou** [comment]
Still on my todo to update my recipe  (I use WPKG).  @wget, does the trailing colon matter in ```/qn:```, and have you had success running the upgrade DURING an active session?

**Comment by wget** [comment]
@klou nope it doesn't. I assumed this was a typo and when using chocolatey or typing in manually the msiexec command, it didn't complain when using the (now quite standard) `/qn` arg.

**Comment by wget** [comment]
@klou I didn't know about WPKG though. Nice discovery for me :) 

From the page https://wpkg.org/:
> A huge database of silent installers

Well: https://wpkg.org/Category:Silent_Installers 😅

**Comment by fraenki** [comment]
> Published: https://chocolatey.org/packages/securepointsslvpn/

@wget Thank you, great job! :+1:

**Comment by klou** [comment]
Finally getting around to this.  Silent install works with the above parameters.  For upgrades, I download the assets locally and create a scheduled task to run at the next restart, but that's probably specific to my environment.  

As far as I'm concerned, this can be closed.
